title: 'ZoOL => Blog'
description: 'rails开发相关'
keywords: 'rails,ruby,git,ubuntu,gem,bloodstone, web2.0, 网站开发'
site_url: 'http://blog.zool.it'  #最后不要带 /
author: 'ZoOL'
google_analytics: 'UA-XXXXX-X'

will_paginate:
  per_page: 10