title: 'Rails中文博客'
header: '我的博客'
description: 'Rails中文博客'

version: '0.1.1'
will_paginate:
  per_page: 10
author: 'ZoOL'
google_analytics: 'UA-XXXXX-X'

links:
  friends: [{name: 'ZoOL => Blog', url: 'http://blog.zool.it'}, {name: 'ZoOL => Project', url: 'http://project.zool.it'}]
